// api/rss.js — Fonction Vercel serverless
// Récupère les flux RSS côté serveur → pas de problème CORS

const FLUX = {
  sante: [
    { url: 'https://www.has-sante.fr/feed/Rss2.jsp?id=p_3081656',  src: 'HAS — Actualités' },
    { url: 'https://www.santepubliquefrance.fr/rss/actualites',     src: 'Santé Publique France' },
    { url: 'https://ansm.sante.fr/rss/actualites',                  src: 'ANSM' },
    { url: 'https://www.inserm.fr/rss/',                            src: 'INSERM' },
    { url: 'https://www.anses.fr/fr/rss.xml',                       src: 'ANSES' },
    { url: 'https://esante.gouv.fr/rss.xml',                        src: 'Numérique en santé' },
    { url: 'https://www.agence-biomedecine.fr/rss.xml',             src: 'Agence Biomédecine' },
    { url: 'https://www.cns.sante.fr/rss.xml',                      src: 'Conférence nationale de santé' },
    { url: 'https://www.france-assos-sante.org/feed',               src: 'France Assos Santé' },
    { url: 'https://www.lemonde.fr/sante/rss_full.xml',             src: 'Le Monde Santé' },
  ],
  social: [
    { url: 'https://www.service-public.fr/rss/actualites.xml',      src: 'Service-Public.fr' },
    { url: 'https://www.vie-publique.fr/rss/actualites.xml',        src: 'Vie Publique' },
    { url: 'https://en3s.fr/feed',                                  src: 'EN3S' },
    { url: 'https://www.defenseurdesdroits.fr/rss.xml',             src: 'Défenseur des droits' },
    { url: 'https://www.fondation-abbe-pierre.fr/rss',              src: 'Fondation Abbé Pierre' },
    { url: 'https://www.lemonde.fr/logement/rss_full.xml',          src: 'Le Monde Logement' },
    { url: 'https://www.documentation-sociale.org/feed',            src: 'Documentation sociale' },
    { url: 'https://www.alternatives-economiques.fr/rss.xml',       src: 'Alternatives Économiques' },
  ],
  medico: [
    { url: 'https://www.cnsa.fr/rss.xml',                           src: 'CNSA' },
    { url: 'https://www.agefiph.fr/rss.xml',                        src: 'Agefiph' },
    { url: 'https://www.handirect.fr/feed/',                        src: 'Handirect' },
    { url: 'https://www.has-sante.fr/feed/Rss2.jsp?id=p_3081452',  src: 'HAS — Recommandations' },
    { url: 'https://www.defenseurdesdroits.fr/rss.xml',             src: 'Défenseur des droits' },
    { url: 'https://www.uniopss.asso.fr/rss.xml',                   src: 'UNIOPSS' },
    { url: 'https://www.fondation-abbe-pierre.fr/rss',              src: 'Fondation Abbé Pierre' },
  ],
  soins: [
    { url: 'https://www.irdes.fr/rss.xml',                          src: 'IRDES' },
    { url: 'https://www.has-sante.fr/feed/Rss2.jsp?id=p_3081452',  src: 'HAS — Recommandations' },
    { url: 'https://www.agence-biomedecine.fr/rss.xml',             src: 'Agence Biomédecine' },
    { url: 'https://www.cns.sante.fr/rss.xml',                      src: 'Conférence nationale de santé' },
    { url: 'https://theconversation.com/fr/sante/articles.atom',    src: 'The Conversation Santé' },
    { url: 'https://www.lemonde.fr/sante/rss_full.xml',             src: 'Le Monde Santé' },
    { url: 'https://www.francetvinfo.fr/sante.rss',                 src: 'Franceinfo Santé' },
  ],
  stms: [
    { url: 'https://www.insee.fr/fr/rss/publications.xml',          src: 'INSEE' },
    { url: 'https://www.inegalites.fr/spip.php?page=backend',       src: 'Obs. des inégalités' },
    { url: 'https://www.observationsociete.fr/feed',                src: 'Centre Obs. Société' },
    { url: 'https://www.credoc.fr/feed',                            src: 'CREDOC' },
    { url: 'https://www.radiofrance.fr/franceculture/rss',          src: 'France Culture' },
    { url: 'https://www.alternatives-economiques.fr/rss.xml',       src: 'Alternatives Économiques' },
  ],
  sp3s: [
    { url: 'https://travail-emploi.gouv.fr/rss/actualites.xml',     src: 'Min. Travail' },
    { url: 'https://www.uniopss.asso.fr/rss.xml',                   src: 'UNIOPSS' },
    { url: 'https://drees.solidarites-sante.gouv.fr/rss.xml',       src: 'DREES' },
    { url: 'https://www.documentation-sociale.org/feed',            src: 'Documentation sociale' },
    { url: 'https://www.ove-national.education.fr/feed',            src: 'OVE — Vie étudiante' },
  ],
  agreg: [
    { url: 'https://www.ehesp.fr/feed',                             src: 'EHESP' },
    { url: 'https://en3s.fr/feed',                                  src: 'EN3S' },
    { url: 'https://www.irdes.fr/rss.xml',                          src: 'IRDES' },
    { url: 'https://www.insee.fr/fr/rss/publications.xml',          src: 'INSEE' },
    { url: 'https://www.ofdt.fr/rss.xml',                           src: 'OFDT' },
    { url: 'https://www.radiofrance.fr/franceinter/rss',            src: 'France Inter' },
    { url: 'https://www.novethic.fr/feed',                          src: 'Novethic' },
    { url: 'https://www.has-sante.fr/feed/Rss2.jsp?id=p_3081452',  src: 'HAS — Recommandations' },
  ],
};
